FROM mrc.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /source
COPY . .
RUN dotnet restore
RUN dotnet publish -c Relaese -o /publish 

From mrc.microsoft.com/dotnet/sdk:6.0 AS runtime
WORKDIR /app
COPY --from=build /publish /app
ENTRYPOINT ["dotnet", "FurnitureShop.Client.Api.dll"]