version: '3.7'

services:
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - dev
    restart: unless-stopped

  furnitureshop_api:
    image: furnitureshop_api
    depends_on:
      - "furniture_db"
    container_name: furnitreshop_api
    ports: 
      - "8030:80"
    build:
      context: src\FurnitureShop.Api
      dockerfile: Dockerfile
    networks:
      - dev

  furnitureshop_merchant_api:
    image: furnitureshop_merchant_api
    depends_on:
      - "furniture_db"
    container_name: furnitureshop_merchant_api
    ports:
      - "8031:80"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - dev

  furnitureshop_clinet_api:
    image: furnitureshop_client_api
    depends_on:
      - "furniture_db"
    container_name: furnitureshop_client_api
    ports: 
      - "8032:80"
    build:
       context: src\FurnitureShop.Client.Api
       dockerfile: Dockerfile
    networks:
      - dev

  furnitureshop_admin_api:
    image: furnitureshop_admin_api
    depends_on:
      - "furniture_db"
    container_name: furnitureshop_admin_api
    ports:
      - "8032:80"
    build:
      context: src\FurnitureShop.Admin.Api
    networks:
      - dev

  furnitureshop_emailsender_api:
    image: furnitureshop_emailsender_api
    container_name: furnitureshop_emailsender_api
    ports:
      - "8033:80"
    build: 
      context: src\FurnitureShop.EmailSender.API
    networks:
      - dev

    furnitureshop_files_api:
      image: furnitureshop_files_api
      container_name: furnitureshop_files_api
      ports:
        - "8034:80"
      build:
        context: src/FurnitureShop.Files.Api
      networks: 
        - dev


    

  furniture_db:
    image: postgres:latest
    container_name: furniture_db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - customer_data:/var/lib/postgresql/data/ 
    networks:
      - dev

networks:
  dev:
    driver: bridge 
    

volumes:
  customer_data:
  pgadmin: